### PR TITLE
Updated to use bidi mixins

### LINKED ISSUE #2: Support bidirectional styles
To support globalization, this component needs bidirectional styling.

### PR DESCRIPTION
**Pull request by gneatgeek**
### Summary
- Updated to use bidi mixins
- Removed dependencies section from the readme
- General cleanup

Resolves #2

### CODE REVIEW

**Comment by Matt-Butler** [comment]
Does this build for you?

I think this needs the full path:
https://github.com/cerner/terra-table/blob/master/src/webpack.scss#L1-L2

**Comment by Matt-Butler** [comment]
Text is left justified for both `rtl` and `ltr`. For `rtl`, I would expect text to be right justified.

**Comment by gneatgeek** [comment]
> Text is left justified for both rtl and ltr. For rtl, I would expect text to be right justified.

You need to enable bidi support when testing.

```
$terra-bidi: true;

@import 'node_modules/terra-mixins/src/terra-mixins';
```

**Comment by gneatgeek** [comment]
👍

**Comment by bjankord** [comment]
+1

**Pull request merged**
